server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://ep-still-cake-a79pw38a-pooler.ap-southeast-2.aws.neon.tech/auth_db?user=neondb_owner&password=npg_ipZJY3E7wzcn&sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_ipZJY3E7wzcn
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: ultimate-gazelle-158752.upstash.io
      port: 6379
      username: default
      password: gQAAAAAAAmwgAAIgcDJiODgwN2ZjNjRiZmY0ZTM1OTQ0NWQxNjdiODRhYWM5NQ
      ssl:
        enabled: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: b14c18001@smtp-brevo.com
    password: vnd39RFMBLqU8NgO
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: ultimate-gazelle-158752.upstash.io:9092
    properties:
      "[sasl.mechanism]": SCRAM-SHA-256
      "[security.protocol]": SASL_SSL
      "[sasl.jaas.config]": 'org.apache.kafka.common.security.scram.ScramLoginModule required username="default" password="gQAAAAAAAmwgAAIgcDJiODgwN2ZjNjRiZmY0ZTM1OTQ0NWQxNjdiODRhYWM5NQ";'
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      
  cloud:
    config:
      enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  access-token-expiration: 900000 # 15 minutes in ms
  refresh-token-expiration: 604800000 # 7 days in ms
